-- For reference only; the Worker creates these automatically.
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, salt TEXT NOT NULL, hash TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS days (user_id INTEGER NOT NULL, date TEXT NOT NULL, data TEXT NOT NULL, updated INTEGER NOT NULL, srv INTEGER NOT NULL, PRIMARY KEY (user_id, date));
CREATE TABLE IF NOT EXISTS meta (user_id INTEGER PRIMARY KEY, data TEXT NOT NULL, updated INTEGER NOT NULL, srv INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS days_srv ON days (user_id, srv);
